[package]
name = "bacon"
version = "1.2.2-dev"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/bacon"
description = "background rust compiler"
edition = "2018"
keywords = ["rust", "background", "compiler", "watch", "inotify"]
license = "AGPL-3.0"
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"

[dependencies]
argh = "0.1.6"
anyhow = "1.0.44"
cargo_metadata = "0.14.0"
cli-log = "2.0.0"
crossbeam = "0.8.1"
crossterm = "0.21.0"
directories-next = "2.0.0"
notify = "5.0.0-pre.11"
lazy-regex = "2.2.1"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
termimad = "0.16.3"
toml = "0.5.8"
unicode-width = "0.1.9"
vte = "0.8"

[profile.release]
lto = true

[patch.crates-io]
# termimad = { path = "../termimad" }
