[package]
name = "bacon"
version = "1.1.1"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/bacon"
description = "background rust compiler"
edition = "2018"
keywords = ["rust", "background", "compiler", "watch", "inotify"]
license = "AGPL-3.0"
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"

[dependencies]
argh = "0.1.3"
anyhow = "1.0"
cargo_metadata = "0.12"
cli-log = "0.1"
crossbeam = "0.7"
crossterm = "0.17.7"
directories-next = "2.0"
minimad = "=0.6.7"
notify = "5.0.0-pre.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
termimad = "0.9.1"
toml = "0.5"
unicode-width = "0.1.8"
vte = "0.8"

[profile.release]
lto = true

[patch.crates-io]
# termimad = { path = "../termimad" }
