[package]
name = "bacon"
version = "2.0.1"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/bacon"
description = "background rust compiler"
edition = "2021"
keywords = ["rust", "background", "compiler", "watch", "inotify"]
license = "AGPL-3.0"
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"
rust-version = "1.56"

[dependencies]
anyhow = "1.0.49"
cargo_metadata = "0.14.0"
clap = { version = "3.0.14", features = ["derive"] }
cli-log = "2.0.0"
crokey = "0.4"
crossbeam = "0.8.1"
crossterm = "0.22.1"
directories-next = "2.0.0"
notify = "=5.0.0-pre.13"
lazy-regex = "2.2.1"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
termimad = "0.20"
toml = "0.5.8"
unicode-width = "0.1.9"
vte = "0.8"

[profile.release]
lto = true

[patch.crates-io]
# termimad = { path = "../termimad" }
