# This is a preferences file for the bacon tool
# More info at https://github.com/Canop/bacon

# Uncomment and change the value (true/false) to
# specify whether bacon should start in summary mode
#
# summary = true

# Uncomment and change the value (true/false) to
# specify whether bacon should start with lines wrapped
#
# wrap = true

# In "reverse" mode, the focus is at the bottom, item
# order is reversed, and the status bar is on top
#
# reverse = true

# Uncomment and change the key-bindings you want to define
[keybindings]
# ctrl-c = "internal:quit"
# ctrl-q = "internal:quit"
# q = "internal:quit"
# s = "internal:toggle-summary"
# w = "internal:toggle-wrap"
# t = "internal:toggle-backtrace"
# Home = "internal:scroll-to-top"
# End = "internal:scroll-to-bottom"
# Up = "internal:scroll-lines(-1)"
# Down = "internal:scroll-lines(1)"
# PageUp = "internal:scroll-pages(-1)"
# PageDown = "internal:scroll-pages(1)"
# Space = "internal:scroll-pages(1)"
# g = "internal:scroll-to-top"
# shift-g = "internal:scroll-to-bottom"
# k = "internal:scroll-lines(-1)"
# j = "internal:scroll-lines(1)"
